name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.8, 3.9]  # Keep both Python 3.8 and 3.9
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Added a timeout to avoid infinite running jobs
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2
      
      # Step 2: Set up Python version based on matrix
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      
      # Step 3: Install system dependencies (for PDF handling)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils  # Required for PDF text extraction with fulltext
      
      # Step 4: Install Python dependencies, including PyPDF2, fulltext, and chardet
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyPDF2 fulltext chardet  # Explicitly install needed Python packages
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Step 5: Install project dependencies (existing step)
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Step 6: Run doctests (existing step)
      - name: run doctests
        run: |
          python3 -m doctest docsum.py
      
      # Step 7: Run the script on all files in the docs directory (existing step)
      - name: run all files
        run: |
          for file in docs/*; do python3 docsum.py ${file}; done

