name: tests

on:
  push:
    branches:
      - '*'  # This triggers the tests on any branch
  pull_request:
    branches:
      - '*'  # This triggers the tests on any pull request

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install system dependencies (for PDF handling)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils  # Required for PDF text extraction with fulltext

      # Step 4: Install Python dependencies, including PyPDF2, fulltext, and chardet
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyPDF2 fulltext chardet  # Explicitly install needed Python packages
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 5: Run the tests with delays
      - name: Test document summaries with delay
	run: |
          python3 docsum.py docs/declaration
          python3 docsum.py docs/2023.findings-emnlp.945.pdf
          python3 docsum.py docs/hamlet.txt
          python3 docsum.py docs/estados-unidos-admite-haber-perdido-la-pista-de-32000-menores-migrantes-no-acompanados.html
          python3 docsum.py docs/news-mx.txt
          python3 docsum.py docs/constitution-mx.txt
